services:
  DataBase:
    image: postgres:15-alpine
    container_name: rag_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rag_service:
    build:
      context: ./RAG
      dockerfile: Dockerfile
    container_name: rag_ai_service
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./RAG:/app
      - huggingface_cache:/app/models
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 6G
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/api/v1/rag/health" ]
      interval: 20s
      timeout: 20s
      retries: 30

  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    container_name: rag_fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./BACKEND:/app
      - ./RAG:/RAG
      - ./BACKEND/Key:/app/Key
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - USE_CLOUD_DB=${USE_CLOUD_DB}
      - CLOUD_DATABASE_URL=${CLOUD_DATABASE_URL}
      - CLOUD_DB_SSL_CA=/app/Key/ca.pem
      - CLOUD_DB_SSL_CERT=${CLOUD_DB_SSL_CERT}
      - CLOUD_DB_SSL_KEY=${CLOUD_DB_SSL_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - RAG_SERVICE_URL=http://rag_service:8001
    depends_on:
      DataBase:
        condition: service_healthy
      rag_service:
        condition: service_started

  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    container_name: rag_react_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./FRONTEND:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: rag_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      DataBase:
        condition: service_healthy

volumes:
  postgres_data:
  huggingface_cache:
  rag_dataset:
