"""Initial baseline

Revision ID: c6ab8b482a1f
Revises: 
Create Date: 2026-04-16 04:51:22.858654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ab8b482a1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompt_templates', 'query',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('query_logs', 'is_error',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('query_logs', 'is_error',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('prompt_templates', 'query',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
